// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                int32
	Name              string
	ProfilePictureUrl pgtype.Text
	Username          string
	Email             string
	Hash              string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}
