version: '3.8'

volumes:
  bashhistory:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env

    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/vscode/.ssh:cached
      - bashhistory:/commandhistory

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity