// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, username, email, hash, profile_picture_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, username, email, profile_picture_url, created_at, updated_at
`

type CreateUserParams struct {
	Name              string
	Username          string
	Email             string
	Hash              string
	ProfilePictureUrl pgtype.Text
}

type CreateUserRow struct {
	ID                int32
	Name              string
	Username          string
	Email             string
	ProfilePictureUrl pgtype.Text
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Hash,
		arg.ProfilePictureUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
